### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-js-create-an-api-with-express-URJy-_#1]
## Create a todo list API

@stuartpearman Can you take a look at this? It's [hosted here](https://mart1444-khxn-8th0o-1eurjy-.herokuapp.com/) and meets the following criteria:

- [x] Todos should have a field for the todo text and one to indicate whether or not the task has been completed
- [x] User should be able to see all todo items at `/todos`
- [x] POSTing to `/todos` should create a new todo item
- [x] Should be able to `GET`, `PUT`, and `DELETE` to `/todos/:id`
- [x] URLs besides `/todos` and `/todos/:id` respond with a 404 status code
- [x] If a specific todo at `/todos/:id` does not exist, a 404 status code should be returned
- [x] All requests and responses should be in JSON format
- [x] Should have a `.gitignore` file to keep unwanted files and folders from being tracked by git

**Comment by stuartpearman** [comment]
Yoooo, make sure to update all your code with the new fields you're using. The `POST` route, and some others, still reference `name` and `price`.

Let me know when you've made changes.

**Comment by GriffinMartin** [comment]
I fixed it, my bad for not catching that 😛

**Comment by stuartpearman** [comment]
You did fix it! Looks like you have a few to go yet, but this should be a big boost! :shipit:
